### PR TITLE
Fixing issue with static file names for worm genomes

### PR DESCRIPTION
**Pull request by digrigor**
Replacing worm genomes static content file names from species.production_name to species.url so they can be seen from the Web Code.

Slack discussion: https://genomes-ebi.slack.com/archives/C0F90TQ1X/p1638525549222600

### CODE REVIEW

**Comment by digrigor** [comment]
@vsitnik @jgtate

**Comment by vsitnik** [comment]
ok

**Comment by digrigor** [comment]
@vsitnik @ens-ap5 both static files and images have updated file names now. Thanks :)

**Comment by vsitnik** [comment]
ok. cool! thanks!

**Pull request merged**
