### PR TITLE
static content fixes for plants on new branch postreleasefix/eg/51

### PR DESCRIPTION
**Pull request by brunocontrerasmoreira**
Hi @ens-st3 , these are the static content fixes for plants I asked about in #ensemblgenomes

### CODE REVIEW

**Comment by ens-st3** [comment]
You definitely want to remove the Fort Lauderdale agreement note ?

**Comment by brunocontrerasmoreira** [comment]
Yes, these genomes have been public for a long time now, and a paper describing them was published in 2018: https://www.nature.com/articles/s41588-018-0040-0

**Comment by brunocontrerasmoreira** [comment]
I was thinking I could add that reference in release 52, but I could add it to this PR if you prefer,
Bruno

**Comment by ens-st3** [comment]
Next time for that

**Pull request merged**
