### PR TITLE
Static/plants/105

### PR DESCRIPTION
**Pull request by gnaamati**

### CODE REVIEW

**Review by ens-ds23 — COMMENTED** [review]
All fine pending the two below. Commented out text isn't bad per se, but it should probably have an explicit motivation indicated in the document to avoid confusing people who come along later.

**Comment by gnaamati** [comment]
Hi @ens-ds23 , sorry for late reply (new computers and filters).
I think the commented text is there just to have an example on how this should be done.
I don't think there is harm in leaving it there for now but in the future I will remove it.

**Comment by ens-ds23** [comment]
Would it be ok to put an additional one-line comment above each saying `<!-- Example text: -->` or something like that @gnaamati ?

**Comment by gnaamati** [comment]
Hi Dan, sorry for late reply, I'm in Israel and working on and off.
I will update it as you mentioned and resubmit PR later this week

**Comment by ens-ds23** [comment]
Thanks for the updates.

**Pull request merged**
