### PR TITLE
10+ images for cultivars.

### PR DESCRIPTION
**Pull request by gnaamati**
Different images of wheat for the 10+ taken from public archives.

### CODE REVIEW

**Comment by azangru** [comment]
Each of these images, if passed through tinypng.com, can lose quite a lot of weight. For example, Triticum_aestivum_arinalrfor.png can be compressed from 41KB to 16.6KB without perceptible quality loss:

image

@ens-ap5 do we normally ask for the images to be optimised for web, or do we not particularly care?

**Comment by ens-ap5** [comment]
@azangru We don't usually worry about optimisation - the original images were over 700Kb, so resizing them (at my request) was a big improvement!

**Comment by gnaamati** [comment]
Thanks Anne and @azangru!

**Comment by gnaamati** [comment]
Test @gnaamati please ignore :)

**Pull request merged**
