### PR TITLE
Plant static content updated for release 52/105

### PR DESCRIPTION
**Pull request by brunocontrerasmoreira**
Hi @ens-ds23 @gnaamati ,
this PR adds quite a few static content updates to plants, matching approximately the intentions
https://www.ebi.ac.uk/panda/jira/browse/ENSINT-755
https://www.ebi.ac.uk/panda/jira/browse/ENSINT-756
https://www.ebi.ac.uk/panda/jira/browse/ENSINT-786

There is another separate PR from @gnaamati .
Please let us know if you spot errors or when this is picked up in staging so that we can check them,
Bruno

### CODE REVIEW

**Comment by ens-ds23** [comment]
Assuming the copy is correct, this looks good to me. I'll put it up on staging so that you can look at the copy there.

**Comment by brunocontrerasmoreira** [comment]
Please let me know when this is in staging, cannot see the images yet, maybe this is done overnight? Bruno

**Comment by brunocontrerasmoreira** [comment]
> I've had a few issues with the update script and SOP. Should be done soon. I'll let you know.

Sorry, no urgent at all

**Comment by ens-ds23** [comment]
No worries. It was good to spot this early on as it would have caused confusion down the line.

Should all be there now. I've tested it with https://staging-plants.ensembl.org/i/species/Brassica_rapa_ro18.png

**Pull request merged**
