### PR TITLE
static content for plants release 50/103 pending 10+ content

### PR DESCRIPTION
**Pull request by brunocontrerasmoreira**
Hi @imransl @gnaamati ,
the files below have been added/modified in order to update plant static content for release 50/103.
There will be another PR shortly with new content for the wheat 10+ strains.
I have checked how the markdown shows in GitHub but please let me know if there's anything that need correcting,
Bruno

### CODE REVIEW

**Comment by imransl** [comment]
Tagging @azangru as he is relco for 103/50

**Review by ens-ap5 — CHANGES_REQUESTED** [review]
Hi Bruno, could you removed the backslashes before brackets, tildes, etc? I don't know where they come from, but they're not recognised by the Perl Markdown package we use in the webcode. Ta!

**Comment by brunocontrerasmoreira** [comment]
> 
> 
> Hi Bruno, could you removed the backslashes before brackets, tildes, etc? I don't know where they come from, but they're not recognised by the Perl Markdown package we use in the webcode. Ta!

Do you have an example?

**Comment by eead-csic-compbio** [comment]
Just added the reference from the email I CCed you @ens-ap5

**Comment by azangru** [comment]
> > Hi Bruno, could you removed the backslashes before brackets, tildes, etc? I don't know where they come from, but they're not recognised by the Perl Markdown package we use in the webcode. Ta!

> Do you have an example? I guess you mean 55afe13

@brunocontrerasmoreira, looking through the files in this PR, I believe @ens-ap5 meant places like this:

- `\~100 Mb` (plants/species/Selaginella_moellendorffii/Selaginella_moellendorffii_assembly.md)
- `\[5\]` or `\[2\] for both varieties and promoter capture \[11\] only for Kronos. Mutations were called on the IWGSC RefSeq V1.0 assembly using the [Dragen system](https://file.scirp.org/Html/2-1370287_74603.htm) for Cadenza and the MAPS pipeline for Kronos \[12\]` (plants/species/Triticum_aestivum/Triticum_aestivum_variation.md)

There are quite a lot of those escape backslashes still left in the PR. Many are already in the destination branch. Most of those escapes are completely unnecessary. The only meaningful backslash I could see in the PR is the one used for adding new lines in list items.

**Comment by brunocontrerasmoreira** [comment]
Hi @azangru , can you please try again? Thanks

**Review by azangru — APPROVED** [review]

**Pull request merged**
